"""create initial debate schema

Revision ID: d779e845a55c
Revises: 
Create Date: 2026-07-20 22:07:40.639871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd779e845a55c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost >= 0'),
    sa.CheckConstraint('latency_ms >= 0'),
    sa.CheckConstraint('tokens >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_created_at', 'api_usage', ['created_at'], unique=False)
    op.create_index('idx_api_usage_model', 'api_usage', ['model'], unique=False)
    op.create_index('idx_api_usage_model_created', 'api_usage', ['model', 'created_at'], unique=False)
    op.create_index('idx_api_usage_provider', 'api_usage', ['provider'], unique=False)
    op.create_index('idx_api_usage_provider_created', 'api_usage', ['provider', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_model'), 'api_usage', ['model'], unique=False)
    op.create_index(op.f('ix_api_usage_provider'), 'api_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_api_usage_success'), 'api_usage', ['success'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('debates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('FACTUAL', 'REASONING', 'COMPARISON', 'CODING', 'CREATIVE', 'DEBATE', 'EXPLANATION', 'ARCHITECTURE', name='questiontype'), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='debatestatus'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('started_at <= completed_at OR completed_at IS NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debate_created_at', 'debates', ['created_at'], unique=False)
    op.create_index('idx_debate_provider', 'debates', ['provider'], unique=False)
    op.create_index('idx_debate_question_type', 'debates', ['question_type'], unique=False)
    op.create_index('idx_debate_status', 'debates', ['status'], unique=False)
    op.create_index('idx_debate_user_created', 'debates', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_debate_user_id', 'debates', ['user_id'], unique=False)
    op.create_index(op.f('ix_debates_provider'), 'debates', ['provider'], unique=False)
    op.create_index(op.f('ix_debates_question_type'), 'debates', ['question_type'], unique=False)
    op.create_index(op.f('ix_debates_status'), 'debates', ['status'], unique=False)
    op.create_index(op.f('ix_debates_user_id'), 'debates', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('debate_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5'),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index('idx_feedback_debate_id', 'feedback', ['debate_id'], unique=False)
    op.create_index('idx_feedback_rating', 'feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_feedback_debate_id'), 'feedback', ['debate_id'], unique=False)
    op.create_table('messages',
    sa.Column('debate_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.Enum('RESEARCH', 'OPPONENT', 'CONSENSUS', name='agentrole'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.Enum('INITIAL', 'REBUTTAL', 'CONSENSUS', 'FINAL', name='responsetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('completion_tokens >= 0'),
    sa.CheckConstraint('cost >= 0'),
    sa.CheckConstraint('latency_ms >= 0'),
    sa.CheckConstraint('prompt_tokens >= 0'),
    sa.CheckConstraint('round_number >= 1'),
    sa.CheckConstraint('total_tokens = prompt_tokens + completion_tokens'),
    sa.CheckConstraint('total_tokens >= 0'),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_agent_role', 'messages', ['agent_role'], unique=False)
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_debate_id', 'messages', ['debate_id'], unique=False)
    op.create_index('idx_message_debate_round', 'messages', ['debate_id', 'round_number'], unique=False)
    op.create_index('idx_message_provider', 'messages', ['provider'], unique=False)
    op.create_index('idx_message_success', 'messages', ['success'], unique=False)
    op.create_index(op.f('ix_messages_agent_role'), 'messages', ['agent_role'], unique=False)
    op.create_index(op.f('ix_messages_debate_id'), 'messages', ['debate_id'], unique=False)
    op.create_index(op.f('ix_messages_provider'), 'messages', ['provider'], unique=False)
    op.create_index(op.f('ix_messages_success'), 'messages', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_success'), table_name='messages')
    op.drop_index(op.f('ix_messages_provider'), table_name='messages')
    op.drop_index(op.f('ix_messages_debate_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_role'), table_name='messages')
    op.drop_index('idx_message_success', table_name='messages')
    op.drop_index('idx_message_provider', table_name='messages')
    op.drop_index('idx_message_debate_round', table_name='messages')
    op.drop_index('idx_message_debate_id', table_name='messages')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_index('idx_message_agent_role', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_feedback_debate_id'), table_name='feedback')
    op.drop_index('idx_feedback_rating', table_name='feedback')
    op.drop_index('idx_feedback_debate_id', table_name='feedback')
    op.drop_index('idx_feedback_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_debates_user_id'), table_name='debates')
    op.drop_index(op.f('ix_debates_status'), table_name='debates')
    op.drop_index(op.f('ix_debates_question_type'), table_name='debates')
    op.drop_index(op.f('ix_debates_provider'), table_name='debates')
    op.drop_index('idx_debate_user_id', table_name='debates')
    op.drop_index('idx_debate_user_created', table_name='debates')
    op.drop_index('idx_debate_status', table_name='debates')
    op.drop_index('idx_debate_question_type', table_name='debates')
    op.drop_index('idx_debate_provider', table_name='debates')
    op.drop_index('idx_debate_created_at', table_name='debates')
    op.drop_table('debates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_usage_success'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_provider'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_model'), table_name='api_usage')
    op.drop_index('idx_api_usage_provider_created', table_name='api_usage')
    op.drop_index('idx_api_usage_provider', table_name='api_usage')
    op.drop_index('idx_api_usage_model_created', table_name='api_usage')
    op.drop_index('idx_api_usage_model', table_name='api_usage')
    op.drop_index('idx_api_usage_created_at', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
